name: CI

on: push

jobs:
  xosim:
    if: github.event_name == 'push' && github.repository == 'UCLA-VAST/tapa-fast-cosim'

    runs-on:
      - self-hosted
      - Linux
      - xilinx-tools

    strategy:
      matrix:
        xocl-version:
          - 2023.2

    env:
      XILINX_HLS: /opt/tools/xilinx/Vitis_HLS/${{ matrix.xocl-version }}
      XILINX_VITIS: /opt/tools/xilinx/Vitis/${{ matrix.xocl-version }}
      XILINX_VIVADO: /opt/tools/xilinx/Vivado/${{ matrix.xocl-version }}

    steps:
      - name: Checkout myself
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            cmake \

          # Vivado doesn't like running concurrently for the first time.
          (
            source "${XILINX_VIVADO}"/settings64.sh
            vivado -mode batch -nojournal -nolog
          )
      - name: Install myself
        run: python3 -m pip install .
      - name: Checkout TAPA
        run: git clone https://github.com/UCLA-VAST/tapa
      - name: Install TAPA
        run: tapa/install.sh
      - name: Patch TAPA to run xosim
        working-directory: tapa/apps
        run: |
          for app in *; do
            [[ ! -d "${app}" ]] && continue
            sed -i 's/${hw_emu_xclbin}/'"${app}-hw-xo/g" \
              "${app}"/CMakeLists.txt
            cmake -S"${app}" -B"${app}"/build
          done
      - name: Test myself
        working-directory: tapa
        run: |
          source ${XILINX_VITIS}/settings64.sh
          {
            printf 'all:\n'
            find apps -mindepth 1 -maxdepth 1 -type d \
              -printf '\t+$(MAKE) -C apps/%f/build %f-cosim\n'
          } | make -f -
